### ISSUE TITLE
Kan vi finde nogle kilder på skat.dk for de forskellige påstande/satser?

### ISSUE THREAD

**Issue by Munksgaard** [Munksgaard/investering#5]

**Comment by soborg** [comment]
Der er nævnt flere satser her: https://www.skat.dk/SKAT.aspx?oId=2234844

For eksempel:

> 
> # Skattesatser for gevinster og udbytte (aktieindkomst)
> 
> I 2022 skal du betale:
> 
>   * 27 % i skat af de første 57.200 kr. (2021: 56.500 kr.) i aktieindkomst
>
>   * 42 % af aktieindkomst ud over 57.200 kr. (2021: 56.500 kr.). 
>
>Aktieindkomst er både udbytter og gevinst (fortjeneste) ved salg.
>
>## Hvis du er gift
>
>Er du gift, og bor du sammen med din ægtefælle ved indkomstårets udløb, er beløbsgrænserne det dobbelte. I 2022 skal I betale 27 % af de første 114.400 kr. (27 % af de første 113.000 kr. i 2021) af jeres samlede aktieindkomst og 42 % af aktieindkomst ud over 114.400 kr. (113.000 kr. i 2021).
